# Generated by Django 2.2.10 on 2022-01-03 15:36

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('waist_min_size', models.PositiveIntegerField()),
                ('waist_max_size', models.PositiveIntegerField(blank=True, null=True)),
                ('hip_min_size', models.PositiveIntegerField()),
                ('hip_max_size', models.PositiveIntegerField(blank=True, null=True)),
                ('height_min_size', models.PositiveIntegerField()),
                ('height_max_size', models.PositiveIntegerField(blank=True, null=True)),
                ('available_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title'])),
                ('photo_main', models.ImageField(upload_to='product_photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('proposal', models.FileField(upload_to='product_pdfs/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sale_count', models.IntegerField(default=0)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('colors', models.ManyToManyField(blank=True, related_name='_product_colors_+', to='products.Product')),
                ('sizes', models.ManyToManyField(blank=True, to='products.Size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
