# Generated by Django 2.2.10 on 2021-10-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proposal',
            new_name='proposals',
        ),
    ]
