# Generated by Django 2.2.10 on 2021-10-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211026_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proposals',
            new_name='proposal',
        ),
    ]
