# Generated by Django 2.2.10 on 2021-10-18 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^((?!(0))[0-9]{6,6})$', message='Invalid postal code')]),
        ),
    ]
