export const PRIMARY_AUTH_SUCCESS = "PRIMARY_AUTH_SUCCESS";
export const SECONDARY_AUTH_FAIL = "SECONDARY_AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const ADD_NOTIF = "ADD_NOTIF";
export const REMOVE_NOTIF = "REMOVE_NOTIF";

export const START_LOADING_UI = "START_LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const START_LOADING_BUTTON = "START_LOADING_BUTTON";
export const STOP_LOADING_BUTTON = "STOP_LOADING_BUTTON";

export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const CREATE_ADDRESS = "CREATE_ADDRESSES";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export const FETCH_SELLER_PRODUCTS = "FETCH_SELLER_PRODUCTS";
export const FETCH_SELLER_ORDERS = "FETCH_SELLER_ORDERS";
export const CREATE_SELLER_PRODUCT = "CREATE_SELLER_PRODUCT";
export const DELETE_SELLER_PRODUCT = "DELETE_SELLER_PRODUCT";
export const UPDATE_SELLER_PRODUCT = "UPDATE_SELLER_PRODUCT";

export const FETCH_FAVORITE_PRODUCTS = "FETCH_FAVORITE_PRODUCTS";
export const UPDATE_FAVORITE_PRODUCTS = "UPDATE_FAVORITE_PRODUCTS";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";

export const FETCH_CART = "FETCH_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER = "FETCH_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
