# Generated by Django 2.2.10 on 2021-10-18 19:33

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(9|8|7)\\d{9}$', message='Invalid phone number.')])),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('national_code', models.CharField(blank=True, max_length=6, null=True, validators=[accounts.validators.validate_national_code])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_balance', models.IntegerField(default=False)),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
    ]
