# Generated by Django 2.2.10 on 2021-10-18 07:34

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211017_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_balance',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[accounts.validators.validate_national_code]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(9|8|7)\\d{9}$', message='Invalid phone number.')]),
        ),
    ]
