# Generated by Django 2.2.10 on 2021-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211018_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_balance',
            field=models.IntegerField(default=False),
        ),
    ]
