# Generated by Django 2.2.10 on 2021-10-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesproducts',
            name='products',
        ),
        migrations.RemoveField(
            model_name='favoritesproducts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='FavoritesProducts',
        ),
    ]
