# Generated by Django 2.2.10 on 2021-10-18 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0002_auto_20211010_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_full_name', models.CharField(max_length=120)),
                ('reciver_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(9|8|7)\\d{9}$', message='Invalid phone number.')])),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('postal_address', models.TextField()),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^((?!(0))[0-9]{6,6})$', message='Invalid postal code')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ('-created_at',),
            },
        ),
    ]
